spring.application.name=note
spring.datasource.url=jdbc:mysql://localhost:3306/note_app
spring.datasource.username=root
spring.datasource.password=YourNewPassword123!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true